-- 체대생의 스포츠 바이브코딩: 로그인 없는 즉시 공개 댓글
-- Supabase Dashboard > SQL Editor > New query 에 붙여넣고 Run 하세요.

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  page_path text not null,
  page_title text not null default '',
  name text not null,
  content text not null,
  created_at timestamptz not null default now(),
  is_visible boolean not null default true,
  constraint comments_name_length check (char_length(btrim(name)) between 1 and 30),
  constraint comments_content_length check (char_length(btrim(content)) between 2 and 1000),
  constraint comments_page_path_length check (char_length(page_path) between 1 and 300),
  constraint comments_page_title_length check (char_length(page_title) <= 200)
);

create index if not exists comments_page_path_created_at_idx
  on public.comments (page_path, created_at desc);

alter table public.comments enable row level security;

-- 같은 이름의 정책이 이미 있으면 다시 만들 수 있도록 정리
DROP POLICY IF EXISTS "public_read_visible_comments" ON public.comments;
DROP POLICY IF EXISTS "public_insert_comments" ON public.comments;

create policy "public_read_visible_comments"
on public.comments
for select
to anon, authenticated
using (is_visible = true);

create policy "public_insert_comments"
on public.comments
for insert
to anon, authenticated
with check (
  is_visible = true
  and (page_path like '/columns/%' or page_path like '/columns/%')
  and char_length(btrim(name)) between 1 and 30
  and char_length(btrim(content)) between 2 and 1000
  and char_length(page_path) between 1 and 300
  and char_length(page_title) <= 200
);

-- 익명 방문자는 읽기와 새 댓글 작성만 가능
revoke all on table public.comments from anon, authenticated;
grant select on table public.comments to anon, authenticated;
grant insert (page_path, page_title, name, content) on table public.comments to anon, authenticated;
grant usage, select on sequence public.comments_id_seq to anon, authenticated;
